### ISSUE TITLE
Travis CI build

### ISSUE THREAD

**Issue by marceloboeira** [14-bits/crowd#6]
@mauricioabreu I'll take care of this, I just wanted to figure if there is anything we should look for on matrix of tests (linux specific or even, go versions?) I'm really outdated when it comes to Golang versions and dependency management... it changes faster than javascript frameworks ahhah

**Comment by mauricioabreu** [comment]
go 1.10+

As far as I know, go tries to not break compatibility with older versions. If we use go 1.12+ we are ok.
One recent addition to the language we could use is `go modules` - the built-in dependency package manager

**Comment by marceloboeira** [comment]
nice, are they finally sticking with this one? 💃  I'll double check if I have time tomorrow to prepare the CI build.

**Comment by mauricioabreu** [comment]
go modules? Yes, I think it was already the standard in go 1.11

**Comment by marceloboeira** [comment]
@mauricioabreu done! Habemus Build!
